<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Onboarding Invitation</title>
</head>
<body style="margin:0; padding:0; background:#f8fafc; font-family:Arial, sans-serif; color:#0f172a;">
    <table width="100%" cellpadding="0" cellspacing="0" role="presentation" style="background:#f8fafc; padding:24px;">
        <tr>
            <td align="center">
                <table width="100%" cellpadding="0" cellspacing="0" role="presentation" style="max-width:640px; background:#ffffff; border:1px solid #e2e8f0; border-radius:16px; overflow:hidden;">
                    <tr>
                        <td style="background:#0f766e; padding:24px;">
                            <h1 style="margin:0; color:#ffffff; font-size:24px;">
                                OnboardingFlow
                            </h1>
                            <p style="margin:6px 0 0; color:#ccfbf1; font-size:14px;">
                                Streamline. Track. Review.
                            </p>
                        </td>
                    </tr>

                    <tr>
                        <td style="padding:24px;">
                            <p style="margin:0 0 16px; font-size:16px;">
                                Hi {{ $invite->recipient_name }},
                            </p>

                            <p style="margin:0 0 16px; line-height:1.5; font-size:15px;">
                                You have been invited to complete an onboarding form.
                            </p>

                            @if ($invite->template)
                                <p style="margin:0 0 16px; line-height:1.5; font-size:15px;">
                                    Template: <strong>{{ $invite->template->name }}</strong>
                                </p>
                            @endif

                            @if ($invite->organisation || $invite->role)
                                <p style="margin:0 0 16px; line-height:1.5; font-size:15px;">
                                    @if ($invite->organisation)
                                        Organisation: <strong>{{ $invite->organisation }}</strong><br>
                                    @endif

                                    @if ($invite->role)
                                        Role: <strong>{{ $invite->role }}</strong>
                                    @endif
                                </p>
                            @endif

                            @if ($invite->message)
                                <div style="margin:20px 0; padding:16px; background:#f1f5f9; border-radius:12px; font-size:15px; line-height:1.5;">
                                    {{ $invite->message }}
                                </div>
                            @endif

                            <p style="margin:0 0 20px; line-height:1.5; font-size:15px;">
                                Please use the button below to complete your onboarding details.
                            </p>

                            <p style="margin:0 0 24px;">
                                <a
                                    href="{{ $publicUrl }}"
                                    style="display:inline-block; background:#0f766e; color:#ffffff; text-decoration:none; padding:12px 18px; border-radius:10px; font-weight:bold; font-size:14px;"
                                >
                                    Complete Onboarding
                                </a>
                            </p>

                            <p style="margin:0 0 8px; color:#475569; font-size:13px;">
                                If the button does not work, copy and paste this link into your browser:
                            </p>

                            <p style="margin:0; word-break:break-all; font-size:13px;">
                                <a href="{{ $publicUrl }}" style="color:#0f766e;">
                                    {{ $publicUrl }}
                                </a>
                            </p>

                            @if ($invite->expires_at)
                                <p style="margin:20px 0 0; color:#64748b; font-size:13px;">
                                    This invite expires on {{ $invite->expires_at->format('d M Y') }}.
                                </p>
                            @endif
                        </td>
                    </tr>

                    <tr>
                        <td style="padding:16px 24px; background:#f8fafc; border-top:1px solid #e2e8f0; color:#64748b; font-size:12px;">
                            This is a proof-of-concept onboarding email generated by OnboardingFlow.
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</body>
</html>